pipeline {
    agent any
    tools {
        maven 'Maven-3.9'
    }
    environment {
        AWS_REGION = "us-east-1"
        ECR_URI = "799517508141.dkr.ecr.us-east-1.amazonaws.com/gitops-app"
        SONAR_HOST_URL = "http://100.30.238.163:9000"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                dir('employee-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('employee-service') {
                    withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                        sh """
                        mvn sonar:sonar \
                          -Dsonar.projectKey=employee-api \
                          -Dsonar.host.url=$SONAR_HOST_URL \
                          -Dsonar.login=$SONAR_TOKEN
                        """
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh """
                docker build -t employee-api:${IMAGE_TAG} employee-service
                docker tag employee-api:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}
                docker tag employee-api:${IMAGE_TAG} ${ECR_URI}:latest
                """
            }
        }

        stage('Push to ECR') {
            steps {
                sh """
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_URI}
                docker push ${ECR_URI}:${IMAGE_TAG}
                docker push ${ECR_URI}:latest
                """
            }
        }
    }

    post {
        success {
            echo "✅ Build & Push Successful"
        }

        failure {
            echo "❌ Pipeline Failed"
        }
    }
}
