pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/mohammedashfakh/aws-cicd-jenkins-docker-demo'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
                sh 'ls -l target/'   // debug: verify jar exists
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t my-app .'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker rm -f my-app-container || true
                docker run -d -p 8081:8080 --name my-app-container my-app
                '''
            }
        }
    }
}
